// Signature Immersive Experience (SIE)
// A hybrid, interdisciplinary experiential learning programme combining a VIRTUAL
// phase with an IN-COUNTRY IMMERSION (Kenya, 2026 cohort). Designed for non-clinical
// Health Missions students to gain direct exposure to how health systems function,
// how innovation is applied in practice, and what employment pathways exist —
// through site visits, partner-defined projects and structured reflection.

export const SIE_PHASES = ["Virtual Phase", "In-Country Immersion"] as const;
export type SiePhase = typeof SIE_PHASES[number];

/** The three pillars of the immersion experience. */
export const SIE_ACTIVITIES = ["Site Visits", "Partner Projects", "Structured Reflection"] as const;
export type SieActivity = typeof SIE_ACTIVITIES[number];

/** Exposure outcomes the programme is designed to produce. */
export const SIE_EXPOSURE_AREAS = [
  "Health System Function",
  "Innovation in Practice",
  "Employment Pathways",
] as const;
export type SieExposureArea = typeof SIE_EXPOSURE_AREAS[number];

/** Academic backgrounds — the programme is explicitly interdisciplinary & non-clinical. */
export const SIE_DISCIPLINES = [
  "Business & Entrepreneurship",
  "Computer Science",
  "Engineering",
  "Social Sciences",
  "Public Policy",
  "Data Science",
] as const;
export type SieDiscipline = typeof SIE_DISCIPLINES[number];

export interface SieCohort {
  id: string;
  name: string;
  year: number;
  country: string;
  /** Recruitment / participation funnel */
  applied: number;
  selected: number;
  completedVirtual: number;
  travelledInCountry: number;
  completedProgramme: number;
  female: number;
  /** Delivery volume */
  siteVisits: number;
  partnerOrgs: number;
  partnerProjects: number;
  reflectionSessions: number;
  /** Self-reported exposure gain, out of 5, per exposure area */
  exposure: Record<SieExposureArea, number>;
  /** Participants by academic discipline */
  disciplines: Record<SieDiscipline, number>;
  /** Hours delivered in each phase */
  hours: Record<SiePhase, number>;
  /** Outcomes generated by the immersion */
  employmentLeads: number;
  projectsAdopted: number;   // partner-defined projects taken forward by the host
  satisfaction: number;      // out of 5
}

export const sieCohorts: SieCohort[] = [
  {
    id: "SIE01", name: "SIE Pilot Cohort", year: 2024, country: "Rwanda",
    applied: 64, selected: 24, completedVirtual: 22, travelledInCountry: 20, completedProgramme: 19,
    female: 11,
    siteVisits: 6, partnerOrgs: 5, partnerProjects: 5, reflectionSessions: 8,
    exposure: { "Health System Function": 4.1, "Innovation in Practice": 4.0, "Employment Pathways": 3.7 },
    disciplines: {
      "Business & Entrepreneurship": 7, "Computer Science": 4, "Engineering": 3,
      "Social Sciences": 4, "Public Policy": 3, "Data Science": 3,
    },
    hours: { "Virtual Phase": 32, "In-Country Immersion": 60 },
    employmentLeads: 6, projectsAdopted: 2, satisfaction: 4.2,
  },
  {
    id: "SIE02", name: "SIE Cohort II", year: 2025, country: "Rwanda",
    applied: 98, selected: 32, completedVirtual: 30, travelledInCountry: 28, completedProgramme: 27,
    female: 15,
    siteVisits: 9, partnerOrgs: 7, partnerProjects: 8, reflectionSessions: 12,
    exposure: { "Health System Function": 4.4, "Innovation in Practice": 4.3, "Employment Pathways": 4.0 },
    disciplines: {
      "Business & Entrepreneurship": 9, "Computer Science": 6, "Engineering": 4,
      "Social Sciences": 5, "Public Policy": 4, "Data Science": 4,
    },
    hours: { "Virtual Phase": 40, "In-Country Immersion": 72 },
    employmentLeads: 11, projectsAdopted: 4, satisfaction: 4.5,
  },
  {
    id: "SIE03", name: "SIE Cohort III — Kenya", year: 2026, country: "Kenya",
    applied: 132, selected: 40, completedVirtual: 38, travelledInCountry: 36, completedProgramme: 35,
    female: 20,
    siteVisits: 12, partnerOrgs: 10, partnerProjects: 11, reflectionSessions: 16,
    exposure: { "Health System Function": 4.6, "Innovation in Practice": 4.5, "Employment Pathways": 4.3 },
    disciplines: {
      "Business & Entrepreneurship": 11, "Computer Science": 8, "Engineering": 5,
      "Social Sciences": 6, "Public Policy": 5, "Data Science": 5,
    },
    hours: { "Virtual Phase": 48, "In-Country Immersion": 80 },
    employmentLeads: 17, projectsAdopted: 6, satisfaction: 4.7,
  },
];

/** Individual site visits made during the in-country immersion. */
export interface SieSiteVisit {
  id: string;
  cohortId: string;
  host: string;
  hostType: "Referral Hospital" | "Health Startup" | "Regulator / Ministry" | "Research Institute" | "Health Manufacturer";
  year: number;
  country: string;
  students: number;
  /** Which exposure area this visit was designed to deliver */
  focus: SieExposureArea;
  insightScore: number; // student-rated value of the visit, out of 5
}

export const sieSiteVisits: SieSiteVisit[] = [
  { id: "SV01", cohortId: "SIE01", host: "King Faisal Hospital",        hostType: "Referral Hospital",    year: 2024, country: "Rwanda", students: 20, focus: "Health System Function", insightScore: 4.3 },
  { id: "SV02", cohortId: "SIE01", host: "Babyl Rwanda",                hostType: "Health Startup",       year: 2024, country: "Rwanda", students: 20, focus: "Innovation in Practice", insightScore: 4.4 },
  { id: "SV03", cohortId: "SIE01", host: "Rwanda FDA",                  hostType: "Regulator / Ministry", year: 2024, country: "Rwanda", students: 19, focus: "Health System Function", insightScore: 3.9 },
  { id: "SV04", cohortId: "SIE01", host: "Rwanda Biomedical Centre",    hostType: "Research Institute",   year: 2024, country: "Rwanda", students: 18, focus: "Employment Pathways",    insightScore: 3.8 },
  { id: "SV05", cohortId: "SIE01", host: "Zipline Distribution Centre", hostType: "Health Startup",       year: 2024, country: "Rwanda", students: 20, focus: "Innovation in Practice", insightScore: 4.7 },
  { id: "SV06", cohortId: "SIE01", host: "BioNTech Kigali",             hostType: "Health Manufacturer",  year: 2024, country: "Rwanda", students: 17, focus: "Employment Pathways",    insightScore: 4.1 },

  { id: "SV07", cohortId: "SIE02", host: "King Faisal Hospital",        hostType: "Referral Hospital",    year: 2025, country: "Rwanda", students: 28, focus: "Health System Function", insightScore: 4.4 },
  { id: "SV08", cohortId: "SIE02", host: "Zipline Distribution Centre", hostType: "Health Startup",       year: 2025, country: "Rwanda", students: 28, focus: "Innovation in Practice", insightScore: 4.8 },
  { id: "SV09", cohortId: "SIE02", host: "Rwanda FDA",                  hostType: "Regulator / Ministry", year: 2025, country: "Rwanda", students: 26, focus: "Health System Function", insightScore: 4.1 },
  { id: "SV10", cohortId: "SIE02", host: "BioNTech Kigali",             hostType: "Health Manufacturer",  year: 2025, country: "Rwanda", students: 27, focus: "Employment Pathways",    insightScore: 4.3 },
  { id: "SV11", cohortId: "SIE02", host: "Rwanda Biomedical Centre",    hostType: "Research Institute",   year: 2025, country: "Rwanda", students: 25, focus: "Health System Function", insightScore: 4.0 },
  { id: "SV12", cohortId: "SIE02", host: "Babyl Rwanda",                hostType: "Health Startup",       year: 2025, country: "Rwanda", students: 28, focus: "Innovation in Practice", insightScore: 4.5 },
  { id: "SV13", cohortId: "SIE02", host: "Ministry of Health Rwanda",   hostType: "Regulator / Ministry", year: 2025, country: "Rwanda", students: 24, focus: "Employment Pathways",    insightScore: 4.2 },
  { id: "SV14", cohortId: "SIE02", host: "Kigali Health Institute",     hostType: "Research Institute",   year: 2025, country: "Rwanda", students: 26, focus: "Health System Function", insightScore: 4.1 },
  { id: "SV15", cohortId: "SIE02", host: "Insightiv AI",                hostType: "Health Startup",       year: 2025, country: "Rwanda", students: 27, focus: "Innovation in Practice", insightScore: 4.6 },

  { id: "SV16", cohortId: "SIE03", host: "Kenyatta National Hospital",  hostType: "Referral Hospital",    year: 2026, country: "Kenya", students: 36, focus: "Health System Function", insightScore: 4.6 },
  { id: "SV17", cohortId: "SIE03", host: "Ministry of Health Kenya",    hostType: "Regulator / Ministry", year: 2026, country: "Kenya", students: 35, focus: "Health System Function", insightScore: 4.4 },
  { id: "SV18", cohortId: "SIE03", host: "M-TIBA / CarePay",            hostType: "Health Startup",       year: 2026, country: "Kenya", students: 36, focus: "Innovation in Practice", insightScore: 4.8 },
  { id: "SV19", cohortId: "SIE03", host: "Ilara Health",                hostType: "Health Startup",       year: 2026, country: "Kenya", students: 34, focus: "Innovation in Practice", insightScore: 4.7 },
  { id: "SV20", cohortId: "SIE03", host: "KEMRI",                       hostType: "Research Institute",   year: 2026, country: "Kenya", students: 35, focus: "Health System Function", insightScore: 4.5 },
  { id: "SV21", cohortId: "SIE03", host: "Pharmaceutical Society KE",   hostType: "Regulator / Ministry", year: 2026, country: "Kenya", students: 33, focus: "Employment Pathways",    insightScore: 4.2 },
  { id: "SV22", cohortId: "SIE03", host: "Revital Healthcare",          hostType: "Health Manufacturer",  year: 2026, country: "Kenya", students: 34, focus: "Employment Pathways",    insightScore: 4.4 },
  { id: "SV23", cohortId: "SIE03", host: "Access Afya",                 hostType: "Health Startup",       year: 2026, country: "Kenya", students: 35, focus: "Innovation in Practice", insightScore: 4.6 },
  { id: "SV24", cohortId: "SIE03", host: "Aga Khan University Hospital",hostType: "Referral Hospital",    year: 2026, country: "Kenya", students: 36, focus: "Health System Function", insightScore: 4.5 },
  { id: "SV25", cohortId: "SIE03", host: "Amref Health Africa",         hostType: "Research Institute",   year: 2026, country: "Kenya", students: 34, focus: "Employment Pathways",    insightScore: 4.3 },
  { id: "SV26", cohortId: "SIE03", host: "Jacaranda Health",            hostType: "Health Startup",       year: 2026, country: "Kenya", students: 35, focus: "Innovation in Practice", insightScore: 4.7 },
  { id: "SV27", cohortId: "SIE03", host: "Kenya Medical Supplies Auth.",hostType: "Regulator / Ministry", year: 2026, country: "Kenya", students: 32, focus: "Health System Function", insightScore: 4.1 },
];
